### ISSUE TITLE
Project logo jumping

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/dse-static-cookiecutter#11]
As this could be an individual design decision, I don't agree to implement it in the general layout. The logo in the navbar has two sizes and is shown crossing the bottom line of the navbar when loading a page:

![Bildschirmfoto 2023-04-11 um 13 42 53](https://user-images.githubusercontent.com/11441262/231153059-a85a0187-9fd4-410a-9255-8d4f10d86814.png)

Once one scrolls further down on the page it jumps to a smaller version
![Bildschirmfoto 2023-04-11 um 13 42 58](https://user-images.githubusercontent.com/11441262/231153135-bb713634-5865-4da8-8389-e7901c26e725.png)

Better would be a consistent placement of the project logo within the navbar.

**Comment by linxOD** [comment]
expected behavior: disable /js/navScroll.js and it will stop
