### ISSUE TITLE
dse-static-site Project Generator defaults preventing successful completion of Quickstart guide

### ISSUE THREAD

**Issue by dominikfill** [acdh-oeaw/dse-static-cookiecutter#56]
Hi,

Step 12/14 of the **dse-static-site project generator** consists of selecting the `search_engine`. The default value provided is set to `typesense`.

<img src="https://github.com/acdh-oeaw/dse-static-cookiecutter/assets/45312697/c269edb7-bdca-4063-9b6f-85926985909e" width=50%>

Accepting this default value makes completing the step 

https://github.com/acdh-oeaw/dse-static-cookiecutter/blob/76853bd1bf82ba731dd5807123221ca1f9c5c01b/README.md?plain=1#L33

of the Quickstart guide impossible, as choosing `typesense` deletes `build_index.sh`, as defined in `hooks/post_gen_project.py`

https://github.com/acdh-oeaw/dse-static-cookiecutter/blob/76853bd1bf82ba731dd5807123221ca1f9c5c01b/hooks/post_gen_project.py#L10-L16

This could maybe cause confusion for new users, as one could expect that using the defaults provided would allow for successful completion of the Quickstart guide.

**Comment by csae8092** [comment]
staticSearch support dropped, therefore this issue should be resolved
