### ISSUE TITLE
document permissions for ghp wf

### ISSUE THREAD

**Issue by cfhaak** [acdh-oeaw/dse-static-cookiecutter#57]
`remote: Permission to someone/dse-static-test.git denied to github-actions[bot]. 

 

 fatal: unable to access 'https://github.com/someone/dse-static-test.git/': The requested URL returned error: 403 

 

 Error: Action failed with "The process '/usr/bin/git' failed with exit code 128" `

Even though this error is expected to happen under default settings it would be of great help for new users if the correct settings for the repo would be hinted in the docs. -> Set "Setting – Actions – General – Workflow Permissions"  to  "Read & Write Permissions".

**Comment by csae8092** [comment]
I think this can be closed as the new gh-action worfklow file `build.yml` 
* does not use gh-pages branch any more
* sets some permissions 
```
v
