### ISSUE TITLE
Ant creates malformed html files

### ISSUE THREAD

**Issue by dominikfill** [acdh-oeaw/dse-static-cookiecutter#58]
Hi,

Step 13/14 of the **dse-static-site project generator** asks for a directory name in an external repo to load data from, if desired.

https://github.com/acdh-oeaw/dse-static-cookiecutter/blob/76853bd1bf82ba731dd5807123221ca1f9c5c01b/README.md?plain=1#L26

#

When not using the provided default value but instead leaving the value for `data_dir` blank, `./data/editions` in the generated project folder gets populated with the following example XML files:  

<img src="https://github.com/acdh-oeaw/dse-static-cookiecutter/assets/45312697/2093ed26-3da4-4c80-8b7d-5747308d9c42" width=75%> &nbsp; &nbsp;

#
When then continuing on with the steps listed in the Quickstart guide, running the command 
https://github.com/acdh-oeaw/dse-static-cookiecutter/blob/76853bd1bf82ba731dd5807123221ca1f9c5c01b/README.md?plain=1#L33
fails:

```console
dominik@THINKPAD-P15:~/acdh/dse-static$ ./shellscripts/build_index.sh
build index
Buildfile: /home/dominik/acdh/dse-static/static-search/build.xml

init:
     [echo] Initializing staticSearch build using codebase in /home/dominik/acdh/dse-static/static-search...
     [echo] Deleting old products...
     [echo] Creating new static search directory: /home/dominik/acdh/dse-static/html/static-search
    [mkdir] Created dir: /home/dominik/acdh/dse-static/html/static-search
     [echo] Running staticSearch build based on config file:
     [echo]     /home/dominik/acdh/dse-static/ss_config.xml

validate:
     [echo] Validating /home/dominik/acdh/dse-static/html for well-formedness
[xmlvalidate] /home/dominik/acdh/dse-static/html/D_000002-003-000.html:97:21: The element type "br" must be terminated by the matching end-tag "</br>".

BUILD FAILED
/home/dominik/acdh/dse-static/static-search/build.xml:212: Could not validate document /home/dominik/acdh/dse-static/html/D_000002-003-000.html

Total time: 0 seconds
```
It looks like `ant` creates malformed .html files. 
When commenting out the following lines in `./build.xml`

https://github.com/acdh-oeaw/dse-static-cookiecutter/blob/76853bd1bf82ba731dd5807123221ca1f9c5c01b/%7B%7Bcookiecutter.directory_name%7D%7D/build.xml#L66-L77

and re-running `ant`,  running `./shellscripts/build_index.sh` finishes without error.

**Comment by csae8092** [comment]
support for staticSearch was dropped, closing this issue
