### ISSUE TITLE
Limit length of typesense-result-buttons

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/dse-static-cookiecutter#72]
A minor issue but as there are no linebreaks in buttons the layout gets corrupt if a button is too long. You can try this out when searching for "Kreis von Herren" here: https://schnitzler-briefe.acdh.oeaw.ac.at/search.html

The solution would be to limit the content of the buttons to a max length of 115 chars.

**Comment by csae8092** [comment]
This should be handled in the individual projects

**Comment by martinantonmueller** [comment]
That's what I call an easy fix! ;-)

**Comment by martinantonmueller** [comment]
ChagtGPT was my best friend:

instantsearch.widgets.hits({
  container: "#hits",
  cssClasses: {
    item: "w-100"
  },
  templates: {
    empty: "Keine Resultate für <q>{{ query }}</q>",
    item(hit, { html, components }) {
      // Helper function to truncate label
      const truncateLabel = (label) => label.length > 115 ? label.substring(0, 112) + '...' : label;

      return html`
        <h3><a href="${hit.id}.html">${hit.title}</a></h3>
        <p>${hit._snippetResult.full_text.matchedWords.length > 0 ? components.Snippet({ hit, attribute: 'full_text' }) : ''}</p>
        ${hit.persons.map((item) => html`<a href='${item.id}.html'><span class="badge rounded-pill m-1 bg-warning">${truncateLabel(item.label)}</span></a>`)}
        <br />
        ${hit.places.map((item) => html`<a href='${item.id}.html'><span class="badge rounded-pill m-1 bg-info">${truncateLabel(item.label)}</span></a>`)}
        <br />
        ${hit.works.map((item) => html`<a href='${item.id}.html'><span class="badge rounded-pill m-1 bg-success">${truncateLabel(item.label)}</span></a>`)}
        <br />`;
    },
  },
})
