### ISSUE TITLE
numbering of search results (typesense)

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/dse-static-cookiecutter#74]
Not a big thing, but: If I have more than 10 search results these are split over several pages. This is desired. What is more difficult: The results are newly numbered on each page starting from 1 to 10. That makes it difficult to know on which page one currently is. 
I.e.
https://schnitzler-tagebuch.acdh.oeaw.ac.at/search.html
search for "bei Mama", 303 results

it would be nicer if the results on page 2 would be 11–20, 3 21–30 and so on

**Comment by csae8092** [comment]
this is actually an implementation issue of schnitzler-tagebuch; 
dse-static does not provide any search views
